### ISSUE TITLE
Practica 2: Diseño de objeto 3D

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo-edith#2]
[PRACTICA 2 DISEÑO DE OBJETOS 3D.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo-edith/files/8352639/PRACTICA.2.DISENO.DE.OBJETOS.3D.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Buen trabajo, cumple con todos los puntos a evaluar 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
